---
abstract: 'colors output of `tar tvf`'
author:
  - 'Marc Abramowitz <marc@marc-abramowitz.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300014, CPAN::Meta::Converter version 2.120921'
keywords:
  - tar
  - color
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-TarColor
resources:
  bugtracker: https://github.com/msabramo/tarcolor/issues
  homepage: https://github.com/msabramo/tarcolor
  repository: https://github.com/msabramo/tarcolor
version: 0.011
